### ISSUE TITLE
Adding this fork to Packagist

### ISSUE THREAD

**Issue by skylerkatz** [jsmitty12/phpWhois#10]
Hey @jsmitty12 do you have any thoughts about adding this fork of the repo to packagist since the original is no longer being updated?

**Comment by jsmitty12** [comment]
Thank you for asking about this, Skyler. It's something that I considered
very briefly, but I didn't feel like it would be useful to anyone. Until
you asked. I'm working on adding it to Packagist now.

Thank you for your encouragement. Please feel free to submit a pull request
for any bug fixes you want to contribute!

Josh


--
email: jsmith@jssm.com
cell: 330-280-0065

"And whatever you do, whether in word or deed, do it all in the name of the
Lord Jesus. " -Colossians 3:17
