### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by kotuk** [jsmitty12/phpWhois#36]
Problem 1
    - The requested package jsmitty12/phpwhois No version set (parsed as 1.0.0) is satisfiable by jsmitty12/phpwhois[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by kotuk** [comment]
on other server:  Problem 1
    - The requested package jsmitty12/phpwhois No version set (parsed as 1.0.0) is satisfiable by jsmitty12/phpwhois[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for jsmitty12/phpwhois ^5.4.0 -> satisfiable by jsmitty12/phpwhois[v5.4.0].
    - roave/security-advisories dev-master conflicts with jsmitty12/phpwhois[v5.4.0].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].

**Comment by jsmitty12** [comment]
This is fixed in version 5.4.1.
