### ISSUE TITLE
Fatal errors running tests with PHPUnit 8

### ISSUE THREAD

**Issue by module17** [jsmitty12/phpWhois#44]
Running PHPUnit 8.0.4 and PHP 7.2.15.

`PHP Fatal error:  Declaration of phpWhois\Handlers\GtldHandlerTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in phpWhois/tests/Handlers/GtldHandlerTest.php on line 75`

**Comment by jsmitty12** [comment]
Fixed with PR #70
